### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by serhatsezer** [theappbusiness/ConfigGenerator#5] opened 2016-08-31 14:57 UTC
You build a tool for ease to use for other developers, but it is not clear how to use in our project. describe it more clearly. How we create mapping file etc.

**Comment by samdods** [comment] 2016-12-15 17:21
closing as duplicate of https://github.com/theappbusiness/ConfigGenerator/issues/1

**Closed as completed by samdods** 2016-12-15 17:21 UTC
